version: '3'

services:
  app:
    build:
      context: .
      dockerfile: _docker/dev/app/Dockerfile
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: localhost
    container_name: chat-server_app

